### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fractune** [zeroruka/GI_Assets#5]
Is there a point in NSFW avatars section if there are no nsfw mods for grasscutter/genshin? Is it just for personal enjoyment

**Comment by BobbyWibowo** [comment]
You are supposed to use them in-game with Special K
They are already in DDS format, with matching hash names with the in-game assets, allowing "plug & play"

Of course I believe I do not have to elaborate on whether it's allowed or not if you play on the official server

**Comment by Fractune** [comment]
Isn't Special K only a tool used to import textures and/or models into the game?

> Of course I believe I do not have to elaborate on whether it's allowed or not if you play on the official server
FYI I'm speaking about local server 'cause If I played on official I'm sure there would be a high ban risk

**Comment by BobbyWibowo** [comment]
Obviously it's for your own eyes only experience
I figured it should have been obvious

Otherwise the question wouldn't make much sense to me, as if you were insinuating that personal enjoyment seemed unlikely to be the point of it all, lmao

---

Though yeah, no wonder your GitHub username gave me deja vu

If you're dreaming of having your own modded textures be visible to other players, I believe the other guy in https://github.com/Akebi-Group/Akebi-GC/issues/29 gave enough explanations

**Comment by BobbyWibowo** [comment]
Anyways the root issue is that the question started with "Is there any point to X"

As for the other question, no, there are no such mods publicly available for the time being

**Comment by Fractune** [comment]
Alright, that's all the info I needed. Thanks for understanding
