### ISSUE TITLE
Cannot edit downloaded textures with GIMP

### ISSUE THREAD

**Issue by kagura114** [zeroruka/GI_Assets#6]
GIMP version: GIMP 2.10.30
What's the problem: I tried to edit the dds files in nsfw folder and got these errors
`Unsupported DXGI format (99)`
`Unsupported DXGI format (98)`
I don't know how to edit the dds files with GIMP and I found this issue [https://gitlab.gnome.org/GNOME/gimp/-/issues/5411](url)
So I think there need to be an explanation on how to edit with gimp,

**Comment by Fractune** [comment]
If there would be an explanation about that then it would be on their official docs and not here obviously. Have you tried searching for answers on google before asking?

**Comment by kagura114** [comment]
I know I cant edit dds with gimp, i just want to know what the method 1,for testing,mean

**Comment by zeroruka** [comment]
Method 1 uses ModelChanger to change skins, therefore there's no need to restart the game whenever you make a change to the skin. That's why it's better for testing the textures that you are editing.
Method 1 doesn't require using GIMP, you could very well use any editing software you like. It's only the injection method that's different.

Method 2 requires restarting the game for newly edited texture to update, therefore it is not as good if you are testing your textures.

**Comment by kagura114** [comment]
Okay I got it
